#ifndef MAILBOXPLUGIN_GLOBAL_H
#define MAILBOXPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef MAILBOXPLUGIN_LIB
# define MAILBOXPLUGIN_EXPORT Q_DECL_EXPORT
#else
# define MAILBOXPLUGIN_EXPORT Q_DECL_IMPORT
#endif

#endif // MAILBOXPLUGIN_GLOBAL_H
