#ifndef CHATMESSAGEPLUGIN_GLOBAL_H
#define CHATMESSAGEPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef CHATMESSAGEPLUGIN_LIB
# define CHATMESSAGEPLUGIN_EXPORT Q_DECL_EXPORT
#else
# define CHATMESSAGEPLUGIN_EXPORT Q_DECL_IMPORT
#endif

#endif // FRIENDLISTPLUGIN_GLOBAL_H