#ifndef FRIENDLISTPLUGIN_GLOBAL_H
#define FRIENDLISTPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef FRIENDLISTPLUGIN_LIB
# define FRIENDLISTPLUGIN_EXPORT Q_DECL_EXPORT
#else
# define FRIENDLISTPLUGIN_EXPORT Q_DECL_IMPORT
#endif

#endif // FRIENDLISTPLUGIN_GLOBAL_H
