#include <QLabel>
#include <QTimer>
#include <QThread>
#include <QQueue>
#include <QWaitCondition>
#include <QMutex>
#include <QHostAddress>
#include <QPainter>
#include <QMouseEvent>
#include <QBitmap>
#include <QByteArray>
#include <QBuffer>
#include <QDomNode>