#ifndef VIDEOCHATPLUGIN_GLOBAL_H
#define VIDEOCHATPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef VIDEOCHATPLUGIN_LIB
# define VIDEOCHATPLUGIN_EXPORT Q_DECL_EXPORT
#else
# define VIDEOCHATPLUGIN_EXPORT Q_DECL_IMPORT
#endif

#endif // VIDEOCHATPLUGIN_GLOBAL_H
