#ifndef SQLSTATEMENTDEFINE
#define SQLSTATEMENTDEFINE

#define  INSERT_USER				"INSERT INTO user_account(PASSWORD,USER_NUMBER,USER_NAME,GENDER,AGE,ADDRESS,OCCUPATIONAL,BIRTHPLACE,SCHOOL,IDENTIGY) VALUES('%1','%2','%3','%4','%5','%6','%7','%8','%9','%10');"

#define  SELECT_USER				"SELECT * FROM user_account WHERE USER_NUMBER = '%1';"

#define  SELECT_USER_IMAGE          "SELECT IMAGE FROM user_account WHERE USER_NUMBER = '%1';"

#define  SELECT_1					"SELECT 1;"

#define  SELECT_CHAT_CONTENT		"SELECT * FROM chat_content WHERE USER_ACCOUNT = '%1' OR FRIEND_ACCOUNT = '%1';"

#define  SELECT_FRIEND				"SELECT * FROM friend WHERE (USER_ACCOUNT = '%1' OR FRIEND_ACCOUNT = '%1') AND USER_ACCOUNT is not NULL AND FRIEND_ACCOUNT is not NULL;"

#define  SELECT_GROUP				"SELECT * FROM groupss WHERE USER_ACCOUNT = '%1';"

#define  SELECT_CHAT_MESSAGE		"SELECT * FROM chat_content WHERE (USER_ACCOUNT = '%1' AND FRIEND_ACCOUNT = '%2') OR (USER_ACCOUNT = '%2' AND FRIEND_ACCOUNT = '%1')"

#define  UPDATE_CHAT_MESSAGE        "UPDATE chat_content SET CHAT_RECORD = '%1' WHERE (USER_ACCOUNT = '%2' AND FRIEND_ACCOUNT = '%3') OR (USER_ACCOUNT = '%2' AND FRIEND_ACCOUNT = '%3')"

#define  INSERT_CHAT_MESSAGE        "INSERT INTO chat_content VALUES('%1', '%2', '%3', '%4', '%5');"

#define  SELECT_GROUP_TYPE			"SELECT DISTINCT GROUP_ACCOUNT FROM group WHERE TYPE = '%1'"

#define  SELECT_GROUP_PEOPLECOUNT   "SELECT * FROM groupss WHERE GROUP_ACCOUNT = '%1'"

#define  SELECT_FIND_USER			"SELECT * FROM %1 WHERE"

#define  INSERT_MAP                 "INSERT INTO friend VALUES('%1','%2','%3')"

#define  INSERT_FRIENDSTATE         "INSERT INTO state_machine VALUES('%1', '%2')"

#define  UPDATEIMAGE                "UPDATE %1 SET IMAGE = ? WHERE USER_NUMBER = '%2'"

#define  UPDATESTATE                "UPDATE state_machine SET STATE = '%1' WHERE USER_NUMBER = '%2'"

#define  SELECT_STATE               "SELECT * FROM state_machine WHERE USER_NUMBER = '%1'"

#endif //SQLSTATEMENTDEFINE