#ifndef SQLSTATEMENTDEFINE
#define SQLSTATEMENTDEFINE

#define  INSERT_USER				"INSERT INTO user_account(PASSWORD,USER_NUMBER,USER_NAME,GENDER,AGE,ADDRESS,OCCUPATIONAL,BIRTHPLACE,SCHOOL,IDENTIGY) VALUES('%1','%2','%3','%4','%5','%6','%7','%8','%9','%10');"

#define  SELECT_USER				"SELECT * FROM user_account WHERE USER_NUMBER = '%1';"

#define  SELECT_1					"SELECT 1;"

#define  SELECT_CHAT_CONTENT		"SELECT * FROM chat_content WHERE USER_ACCOUNT = '%1';"

#define  SELECT_FRIEND				"SELECT * FROM friend WHERE USER_ACCOUNT = '%1';"

#define  SELECT_GROUP				"SELECT * FROM group WHERE USER_ACCOUNT = '%1';"

#define  SELECT_CHAT_MESSAGE		"SELECT CHAT_RECORD FROM chat_content WHERE USER_ACCOUNT = '%1' AND FRIEND_ACCOUNT = '%2'"

#define  SELECT_GROUP_TYPE			"SELECT DISTINCT GROUP_ACCOUNT FROM group WHERE TYPE = '%1'"

#define  SELECT_GROUP_PEOPLECOUNT   "SELECT * FROM group WHERE GROUP_ACCOUNT = '%1'"

#define  SELECT_FIND_USER			"SELECT * FROM %1 WHERE"

#define  INSERT_MAP                 "INSERT INTO friend VALUES('%1','%2','%3')"

#define  UPDATEIMAGE                "UPDATE %1 SET IMAGE = ? WHERE USER_NUMBER = '%2'"

#endif //SQLSTATEMENTDEFINE