#ifndef QQSPACEPLUGIN_GLOBAL_H
#define QQSPACEPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef QQSPACEPLUGIN_LIB
# define QQSPACEPLUGIN_EXPORT Q_DECL_EXPORT
#else
# define QQSPACEPLUGIN_EXPORT Q_DECL_IMPORT
#endif

#endif // QQSPACEPLUGIN_GLOBAL_H
